In [1]:
import os
import pandas
from google.cloud import bigquery
from google.oauth2 import service_account
from google.cloud.bigquery import magics

CONFIGURE THE BIGQUERY SETTINGS

In [2]:
BIGQUERY_PROJECT = 'ironhacks-data'
bigquery_client = bigquery.Client(project=BIGQUERY_PROJECT)

In [3]:
query = """
SELECT * FROM `ironhacks-data.ironhacks_training.weather_data`
"""

In [4]:
query_job = bigquery_client.query(query)
data = query_job.to_dataframe()
data.head()

,date,max_rel_humidity,max_temperature,mean_temperature,min_rel_humidity,min_temperature,potential_water_deficit,precipitation_data,wind_speed
0,2019-09-04,99.9498,25.4570,18.6242,56.4720,11.7913,-3.6142,0.0,3.6461
1,2020-02-16,84.4966,8.6228,3.1896,40.7666,-2.2436,-1.4307,0.0,2.2398
2,2019-12-19,95.9017,2.8886,-3.4884,39.0330,-9.8654,-0.9389,0.0,4.1230
3,2020-02-20,70.0359,0.7939,-4.0254,34.7544,-8.8446,-1.4427,0.0,4.8531
4,2019-12-23,97.1634,13.8411,5.7818,31.2553,-2.2774,-1.2787,0.0,2.3404

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date                     365 non-null    dbdate
 1   max_rel_humidity         365 non-null    float64
 2   max_temperature          365 non-null    float64
 3   mean_temperature         365 non-null    float64
 4   min_rel_humidity         365 non-null    float64
 5   min_temperature          365 non-null    float64
 6   potential_water_deficit  365 non-null    float64
 7   precipitation_data       365 non-null    float64
 8   wind_speed               365 non-null    float64
dtypes: dbdate(1), float64(8)
memory usage: 25.8 KB

In [6]:
data.corr()

/var/folders/l2/cnhff0_n1470l4xf0p7v7l_40000gn/T/ipykernel_15225/2627137660.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.corr()

,max_rel_humidity,max_temperature,mean_temperature,min_rel_humidity,min_temperature,potential_water_deficit,precipitation_data,wind_speed
max_rel_humidity,1.000000,0.165171,0.142654,0.529253,0.113287,0.178500,0.168669,-0.107130
max_temperature,0.165171,1.000000,0.988198,-0.319092,0.947003,-0.183313,0.085175,-0.243966
mean_temperature,0.142654,0.988198,1.000000,-0.237979,0.985032,-0.139413,0.127402,-0.243119
min_rel_humidity,0.529253,-0.319092,-0.237979,1.000000,-0.139980,0.415004,0.302779,0.029954
min_temperature,0.113287,0.947003,0.985032,-0.139980,1.000000,-0.086076,0.171320,-0.235298
potential_water_deficit,0.178500,-0.183313,-0.139413,0.415004,-0.086076,1.000000,0.956646,0.275609
precipitation_data,0.168669,0.085175,0.127402,0.302779,0.171320,0.956646,1.000000,0.231356
wind_speed,-0.107130,-0.243966,-0.243119,0.029954,-0.235298,0.275609,0.231356,1.000000

In [7]:
query = """
SELECT * FROM `ironhacks-data.ironhacks_training.unemployement_data`
"""

In [8]:
query_job = bigquery_client.query(query)
data = query_job.to_dataframe()
data.head()

NotFound: 404 Not found: Table ironhacks-data:ironhacks_training.unemployement_data was not found in location US

Location: US
Job ID: 5a922608-a68c-49c3-a3ae-1790e4e36d81

In [9]:
query = """
SELECT * FROM `ironhacks-data.ironhacks_training.unemployment_data`
"""

In [10]:
query_job = bigquery_client.query(query)
data = query_job.to_dataframe()
data.head()

NotFound: 404 Not found: Table ironhacks-data:ironhacks_training.unemployment_data was not found in location US

Location: US
Job ID: ac0022e5-ee37-424b-a028-3eb51e9993b2

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date                     365 non-null    dbdate
 1   max_rel_humidity         365 non-null    float64
 2   max_temperature          365 non-null    float64
 3   mean_temperature         365 non-null    float64
 4   min_rel_humidity         365 non-null    float64
 5   min_temperature          365 non-null    float64
 6   potential_water_deficit  365 non-null    float64
 7   precipitation_data       365 non-null    float64
 8   wind_speed               365 non-null    float64
dtypes: dbdate(1), float64(8)
memory usage: 25.8 KB

In [12]:
query = """
SELECT * FROM `ironhacks-data.ironhacks_competition.unemployment_data`
"""

In [13]:
query_job = bigquery_client.query(query)
data = query_job.to_dataframe()
data.head()

,uu_id,timeperiod,week_number,countyfips,tract,tract_name,total_claims,edu_8th_or_less,edu_grades_9_11,edu_hs_grad_equiv,...,gender_female,gender_male,gender_na,race_amerindian,race_asian,race_black,race_noanswer,race_hawaiiannative,race_other,race_white
0,f013068de98db1470bd986137a0c6d23,20220416,16,18003,900,"Census Tract 9, Allen County, Indiana",22,0,<NA>,14,...,<NA>,<NA>,0,0,0,11,0,0,<NA>,<NA>
1,21957d5517323845818d87623589e1ba,20220319,12,18089,10400,"Census Tract 104, Lake County, Indiana",111,0,<NA>,108,...,76,35,0,0,0,<NA>,<NA>,0,0,0
2,6a5609f385912113b6f1014b958ed748,20220326,13,18089,11500,"Census Tract 115, Lake County, Indiana",39,0,<NA>,<NA>,...,<NA>,<NA>,0,0,0,39,0,0,0,0
3,46b2882ec4c373527ec33f7bd4f1388d,20220716,29,18089,20700,"Census Tract 207, Lake County, Indiana",14,0,<NA>,<NA>,...,<NA>,<NA>,0,0,<NA>,10,0,0,<NA>,<NA>
4,37495d17e82f7df326bfc2c4c090f7b7,20220409,15,18089,21900,"Census Tract 219, Lake County, Indiana",155,0,<NA>,69,...,90,65,0,0,0,135,<NA>,<NA>,<NA>,<NA>

In [14]:
query = """
SELECT * FROM `ironhacks-data.ironhacks_training.unemployment_data`
"""

In [15]:
query_job = bigquery_client.query(query)
data = query_job.to_dataframe()
data.head()

NotFound: 404 Not found: Table ironhacks-data:ironhacks_training.unemployment_data was not found in location US

Location: US
Job ID: 1b1d0387-cac2-4843-bc84-e771a23b730a

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16833 entries, 0 to 16832
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   uu_id                   16833 non-null  object
 1   timeperiod              16833 non-null  Int64
 2   week_number             16833 non-null  Int64
 3   countyfips              16833 non-null  Int64
 4   tract                   16833 non-null  Int64
 5   tract_name              16833 non-null  object
 6   total_claims            16833 non-null  Int64
 7   edu_8th_or_less         13748 non-null  Int64
 8   edu_grades_9_11         5942 non-null   Int64
 9   edu_hs_grad_equiv       6036 non-null   Int64
 10  edu_post_hs             3246 non-null   Int64
 11  edu_unknown             12031 non-null  Int64
 12  top_category_employer1  16833 non-null  object
 13  top_category_employer2  16833 non-null  object
 14  top_category_employer3  16833 non-null  object
 15  gender_female           3835 non-null   Int64
 16  gender_male             3931 non-null   Int64
 17  gender_na               15868 non-null  Int64
 18  race_amerindian         15285 non-null  Int64
 19  race_asian              14939 non-null  Int64
 20  race_black              7124 non-null   Int64
 21  race_noanswer           10089 non-null  Int64
 22  race_hawaiiannative     16426 non-null  Int64
 23  race_other              8075 non-null   Int64
 24  race_white              6392 non-null   Int64
dtypes: Int64(20), object(5)
memory usage: 3.5+ MB

In [17]:
query = """
SELECT * FROM `ironhacks-data.ironhacks_training.wage_data`
"""

In [18]:
query_job = bigquery_client.query(query)
data = query_job.to_dataframe()
data.head()

NotFound: 404 Not found: Table ironhacks-data:ironhacks_training.wage_data was not found in location US

Location: US
Job ID: 149cc7a7-b0b1-4d18-bcd6-f67aa8525467

In [19]:
query = """
SELECT * FROM `ironhacks-data.ironhacks_competition.unemployment_data`
"""

In [20]:
query_job = bigquery_client.query(query)
data = query_job.to_dataframe()
data.head()

,uu_id,timeperiod,week_number,countyfips,tract,tract_name,total_claims,edu_8th_or_less,edu_grades_9_11,edu_hs_grad_equiv,...,gender_female,gender_male,gender_na,race_amerindian,race_asian,race_black,race_noanswer,race_hawaiiannative,race_other,race_white
0,f013068de98db1470bd986137a0c6d23,20220416,16,18003,900,"Census Tract 9, Allen County, Indiana",22,0,<NA>,14,...,<NA>,<NA>,0,0,0,11,0,0,<NA>,<NA>
1,21957d5517323845818d87623589e1ba,20220319,12,18089,10400,"Census Tract 104, Lake County, Indiana",111,0,<NA>,108,...,76,35,0,0,0,<NA>,<NA>,0,0,0
2,6a5609f385912113b6f1014b958ed748,20220326,13,18089,11500,"Census Tract 115, Lake County, Indiana",39,0,<NA>,<NA>,...,<NA>,<NA>,0,0,0,39,0,0,0,0
3,46b2882ec4c373527ec33f7bd4f1388d,20220716,29,18089,20700,"Census Tract 207, Lake County, Indiana",14,0,<NA>,<NA>,...,<NA>,<NA>,0,0,<NA>,10,0,0,<NA>,<NA>
4,37495d17e82f7df326bfc2c4c090f7b7,20220409,15,18089,21900,"Census Tract 219, Lake County, Indiana",155,0,<NA>,69,...,90,65,0,0,0,135,<NA>,<NA>,<NA>,<NA>

In [21]:
import os
import pandas
from google.cloud import bigquery
from google.oauth2 import service_account
from google.cloud.bigquery import magics

CONFIGURE THE BIGQUERY SETTINGS

In [22]:
BIGQUERY_PROJECT = 'ironhacks-data'
bigquery_client = bigquery.Client(project=BIGQUERY_PROJECT)

In [23]:
query = """
SELECT * FROM `ironhacks-data.ironhacks_competition.unemployment_data`
"""

In [24]:
query_job = bigquery_client.query(query)
data = query_job.to_dataframe()
data.head()

,uu_id,timeperiod,week_number,countyfips,tract,tract_name,total_claims,edu_8th_or_less,edu_grades_9_11,edu_hs_grad_equiv,...,gender_female,gender_male,gender_na,race_amerindian,race_asian,race_black,race_noanswer,race_hawaiiannative,race_other,race_white
0,f013068de98db1470bd986137a0c6d23,20220416,16,18003,900,"Census Tract 9, Allen County, Indiana",22,0,<NA>,14,...,<NA>,<NA>,0,0,0,11,0,0,<NA>,<NA>
1,21957d5517323845818d87623589e1ba,20220319,12,18089,10400,"Census Tract 104, Lake County, Indiana",111,0,<NA>,108,...,76,35,0,0,0,<NA>,<NA>,0,0,0
2,6a5609f385912113b6f1014b958ed748,20220326,13,18089,11500,"Census Tract 115, Lake County, Indiana",39,0,<NA>,<NA>,...,<NA>,<NA>,0,0,0,39,0,0,0,0
3,46b2882ec4c373527ec33f7bd4f1388d,20220716,29,18089,20700,"Census Tract 207, Lake County, Indiana",14,0,<NA>,<NA>,...,<NA>,<NA>,0,0,<NA>,10,0,0,<NA>,<NA>
4,37495d17e82f7df326bfc2c4c090f7b7,20220409,15,18089,21900,"Census Tract 219, Lake County, Indiana",155,0,<NA>,69,...,90,65,0,0,0,135,<NA>,<NA>,<NA>,<NA>